### ISSUE TITLE
ローマ字テーブルを変更したい

### ISSUE THREAD

**Issue by uga-rosa** [oguna/jsmigemo#14]
azikで使いたいので、ローマ字テーブルを変更したいです。ROMAN_ENTRIESを設定可能にすることは可能でしょうか

**Comment by oguna** [comment]
可能ですよ！
小さな修正で済みそうですので近々対応したいと思います。

**Comment by uga-rosa** [comment]
対応ありがとうございます！週末試してみます。

**Comment by uga-rosa** [comment]
すいません。バージョン上げてもらえると。。。

**Comment by oguna** [comment]
npmパッケージのバージョンを0.4.4に上げました。
そのうちローマ字変換のアルゴリズムを破壊的変更する予定なので、
その際は対応方法をQiitaなどで周知したいと思います。

**Comment by uga-rosa** [comment]
ありがとうございます！無事思っていたことができました！
